started setup script

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,16 +1,122 @@
-#!/usr/bin/env bash
+#!/bin/bash
+set -e
 
-# too lazy to write robust script so this is just for basic testing
-ln -sf ~/dotfiles/config/nvim ~/.config/nvim
-ln -sf ~/dotfiles/config/tmux ~/.config/tmux
-ln -sf ~/dotfiles/config/fish ~/.config/fish
+# info logs the given argument at info log level.
+info() {
+    echo "[INFO] " "$@"
+}
 
-# read "Would you like to overwrite your current .config files? (y/n)	" input
-# 
-# 
-# for dir in ../.config do
-# 	if [$input == [yY]] then
-# 		rm -r ~/.config/$dir
-# 	fi
-# 	ln -sf $dir ~/.config/$dir
-# done
+# warn logs the given argument at warn log level.
+warn() {
+    echo "[WARN] " "$@" >&2
+}
+
+# fatal logs the given argument at fatal log level.
+fatal() {
+    echo "[ERROR] " "$@" >&2
+    exit 1
+}
+
+read_os() {
+  OS=$(uname -s)
+}
+
+symlink() {
+    for f in ./config/*; do
+        if [ -d "$f" ]; then
+            ln -sf $f $HOME/.config1/
+            echo "$f"
+        fi
+    done
+}
+
+
+#windows() {
+#    # TODO
+#}
+
+mac() {
+  
+  unzip -q awscliv2.zip
+  ./aws/install --bin-dir /usr/bin
+}
+
+#setup() {
+#  read_os
+#
+#  case $ID in
+#  centos)
+#    yum install -y unzip
+#    install_awscli
+#
+#    # TODO: Determine minimum supported version, for now just carry on assuming ignorance
+#    case $VERSION in
+#    7*)
+#      info "Identified CentOS 7"
+#      INSTALL_RKE2_METHOD='yum' INSTALL_RKE2_TYPE="${type}" ./install.sh
+#
+#      ;;
+#    8*)
+#      info "Identified CentOS 8"
+#      INSTALL_RKE2_METHOD='yum' INSTALL_RKE2_TYPE="${type}" ./install.sh
+#
+#      ;;
+#    esac
+#    ;;
+#
+#  rhel)
+#    yum install -y unzip
+#    install_awscli
+#
+#    case $VERSION in
+#    7*)
+#      info "Identified RHEL 7"
+#
+#      yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.119.2-1.911c772.el7_8.noarch.rpm
+#      INSTALL_RKE2_METHOD='yum' INSTALL_RKE2_TYPE="${type}" ./install.sh
+#      ;;
+#    8*)
+#      info "Identified RHEL 8"
+#
+#      INSTALL_RKE2_METHOD='yum' INSTALL_RKE2_TYPE="${type}" ./install.sh
+#      ;;
+#    esac
+#
+#    ;;
+#
+#  ubuntu)
+#    info "Identified Ubuntu"
+#    # TODO: Determine minimum supported version, for now just carry on assuming ignorance
+#    apt update -y
+#    apt install -y unzip less iptables resolvconf linux-headers-$(uname -r) telnet
+#    hostnamectl set-hostname "$(curl http://169.254.169.254/latest/meta-data/hostname)"
+#
+#    INSTALL_RKE2_METHOD='tar' INSTALL_RKE2_TYPE="${type}" ./install.sh
+#
+#    install_awscli
+#    ;;
+#  amzn)
+#    # awscli already present, only need rke2
+#    yum update -y
+#
+#    case $VERSION in
+#    2)
+#      info "Identified Amazon Linux 2"
+#      INSTALL_RKE2_METHOD='tar' INSTALL_RKE2_TYPE="${type}" ./install.sh
+#      ;;
+#    *)
+#      info "Identified Amazon Linux 1"
+#      INSTALL_RKE2_METHOD='tar' INSTALL_RKE2_TYPE="${type}" ./install.sh
+#      ;;
+#    esac
+#    ;;
+#  *)
+#    fatal "$${ID} $${VERSION} is not currently supported"
+#    ;;
+#  esac
+#}
+
+{
+  read_os
+  symlink
+}
