misc. script refactoring

diff --git a/bin/t b/bin/t
--- a/bin/t
+++ b/bin/t
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 # store pwd in a variable
-ZOXIDE_RESULT=$(zoxide query $1)
+ZOXIDE_RESULT=$(zoxide query "$1")
 
 # if empty exit
 if [ -z "$ZOXIDE_RESULT" ]; then
@@ -8,10 +8,10 @@ if [ -z "$ZOXIDE_RESULT" ]; then
 fi
 
 # get folder name
-FOLDER=$(basename $ZOXIDE_RESULT)
+FOLDER=$(basename "$ZOXIDE_RESULT")
 
 # lookup tmux session name
-SESSION=$(tmux list-sessions | grep $FOLDER | awk '{print $1}')
+SESSION=$(tmux list-sessions | grep "$FOLDER" | awk '{print $1}')
 SESSION=${SESSION//:/}
 
 # check if variable is empty 
@@ -23,14 +23,14 @@ if [ -z "$TMUX" ]; then
     # session does not exist
     echo "session does not exist"
     # jump to directory
-    cd $ZOXIDE_RESULT
+    cd "$ZOXIDE_RESULT" || (echo "Failed to change directory."; exit 1)
     # create session
-    tmux new-session -s $FOLDER
+    tmux new-session -s "$FOLDER"
   else
     # session exists
     echo "session exists"
     # attach to session
-    tmux attach -t $SESSION
+    tmux attach -t "$SESSION"
   fi
 else
   # tmux is active
@@ -39,16 +39,16 @@ else
     # session does not exist
     echo "session does not exist"
     # jump to directory
-    cd $ZOXIDE_RESULT
+    cd "$ZOXIDE_RESULT" || (echo "Failed to change directory."; exit 1)
     # create session
-    tmux new-session -d -s $FOLDER
+    tmux new-session -d -s "$FOLDER"
     # attach to session
-    tmux switch-client -t $FOLDER
+    tmux switch-client -t "$FOLDER"
   else
     # session exists
     echo "session exists"
     # attach to session
     # switch to tmux session
-    tmux switch-client -t $SESSION
+    tmux switch-client -t "$SESSION"
   fi
 fi
